### ISSUE TITLE
visibilities.py fails without printing error message

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#23]
With a non-default data column, it fails silently:

```
$ python ~/projects/ragavi/ragavi/visibilities.py -t scratch/Tarantula_HI_4ch8s.ms --yaxis amplitude --xaxis uvwave -f 0 --datacolumn SC_PEEL_HR0_DATA
Successful readonly open of default-locked table scratch/Tarantula_HI_4ch8s.ms::FIELD: 9 columns, 1 rows
Successful readonly open of auto-locked table scratch/Tarantula_HI_4ch8s.ms::FIELD: 9 columns, 1 rows
Successful readonly open of default-locked table scratch/Tarantula_HI_4ch8s.ms: 36 columns, 5715090 rows
xarrayms.xarray_ms - WARNING - Unable to infer shape of 'FLAG_CATEGORY' column. Ignoring.
$ 
```

Although the log reveals an xarrayms error (tagging @sjperkins):

```==================================== (O_o) ===================================== 
26.04.2019@11:42:01 - __main__ - ERROR - Oops ... ! 
Traceback (most recent call last): 
 File "/home/oms/projects/ragavi/ragavi/visibilities.py", line 1181, in <module> 
   main() 
 File "/home/oms/projects/ragavi/ragavi/visibilities.py", line 1164, in main 
   datacol=datacolumn) 
 File "/home/oms/projects/ragavi/ragavi/visibilities.py", line 756, in blackbox 
   flag=showFlagged, iterate=iterate) 
 File "/home/oms/projects/ragavi/ragavi/visibilities.py", line 604, in prep_yaxis_data 
   ydata = ydata.sel(corr=corr) 
 File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarray/core/dataarray.py", line 849, in sel 
   **indexers_kwargs) 
 File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarray/core/dataset.py", line 1610, in sel 
   self, indexers=indexers, method=method, tolerance=tolerance) 
 File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarray/core/coordinates.py", line 355, in remap_label_indexers 
   obj, v_indexers, method=method, tolerance=tolerance 
 File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarray/core/indexing.py", line 245, in remap_label_indexers 
   dim_indexers = get_dim_indexers(data_obj, indexers) 
 File "/home/oms/.venv/cc/local/lib/python2.7/site-packages/xarray/core/indexing.py", line 213, in get_dim_indexers 
   % invalid) 
ValueError: dimensions or multi-index levels ['corr'] do not exist
```

Whatever the error is, we need to print it to the console and not fail silently.

**Comment by Mulan-94** [comment]
@o-smirnov Ok, so you mean log to both the console and the log file?

**Comment by o-smirnov** [comment]
Yep, I think you should dump the exception traceback to both.

How much detail goes to the console as opposed to the log is something of a matter of taste, but silent failures are a definite no-no.

**Comment by Mulan-94** [comment]
@o-smirnov, the error due to data column name should be gone now
