### ISSUE TITLE
need subset selection in visibilities.py

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#25]
We need to be able to select subsets of data to plot. In particular:

* FIELD (this you already have)

* DATA_DESC_ID 

* SCAN_NUMBER

* arbitrary TaQL query (the above three map to TaQL queries anyway)

* subset (slice) of channels

* subset (slice) of correlations

It would be helpful (and consistent) to just pick up the CubiCal syntax for specifying slices or lists, see its doc below:

```
ddid           = None          # DATA_DESC_IDs to read from the MS. Default reads all. Can be specified as
                                  e.g. "5", "5,6,7", "5~7" (inclusive range), "5:8" (exclusive range),
                                  "5:" (from 5 to last). #metavar:DDID
taql            =               # Additional TaQL selection string. Combined with other selection options.
                                  #metavar:TAQL #type:str
chan            =               # Channels to read (within each DDID). Default reads all. Can be specified as
                                  e.g. "5", "10~20" (10 to 20 inclusive), "10:21" (same), "10:" (from 10 to
                                  end), ":10:2" (0 to 9 inclusive, stepped by 2), "~9:2" (same).
```

Tagging @sjperkins so  he can advise how to do this in xarrayms.

**Comment by sjperkins** [comment]
FIELD_ID, DATA_DESC_ID and SCAN_NUMBER can currently be specified as grouping columns in xds_from_ms

TAQL Queries are on the TODO list https://github.com/ska-sa/xarray-ms/issues/10

**Comment by Mulan-94** [comment]
@sjperkins noted, @o-smirnov should all the data_desc_ids be plotted by default unless specified?

**Comment by o-smirnov** [comment]
> should all the data_desc_ids be plotted by default unless specified?

I would say yes.

**Comment by Mulan-94** [comment]
This has been partially implemented for the SCAN_NUMBER and DATA_DESC_ID now

**Comment by IanHeywood** [comment]
I'm getting the following when I try to select a scan plot using `ragavi-vis`, using either the `scan` parameter or a direct `taql`:

```
$ ragavi-vis --taql SCAN_NUMBER==10 --ms 3C31.ms
04.11.2019@23:26:40 - ragavi       - ERROR      - Invalid DATA_DESC_ID, FIELD_ID, SCAN_NUMBER or TAQL clause
Traceback (most recent call last):
  File "/home/ianh/.local/lib/python2.7/site-packages/ragavi/visibilities.py", line 810, in get_ms
    chunks=chunks)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/dask_ms.py", line 291, in xds_from_ms
    **kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/dask_ms.py", line 229, in xds_from_table
    **kwargs).datasets()
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/reads.py", line 365, in datasets
    self.taql_where)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/ordering.py", line 78, in ordering_taql
    return TableProxy(taql_factory, query, tables=[table_proxy])
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 142, in __call__
    instance = type.__call__(cls, *args, **kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 207, in __init__
    table = ex.impl.submit(factory, *args, **kwargs).result()
  File "/home/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/ianh/.local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 187, in taql_factory
    return pt.taql(query, style=style, tables=tabs)
  File "/home/ianh/.local/lib/python2.7/site-packages/casacore/tables/table.py", line 153, in taql
    tab = table(cmd, tabs, _oper=2)
  File "/home/ianh/.local/lib/python2.7/site-packages/casacore/tables/table.py", line 328, in __init__
    Table.__init__(self, tablename, tabledesc)
RuntimeError: Error in TaQL command: 'using style Python SELECT
	ROWID() as __tablerow__
FROM
	$1
ORDERBY
	TIMEWHERE
	SCAN_NUMBER==10'
  Error in select expression: TIMEWHERE is an unknown column (or keyword) in table /mnt/hgfs/heywood/Astro/Projects/VLA/3C31/spw01/2019/3C31.ms
```

```
$ ragavi-vis --scan 10 --ms 3C31.ms
04.11.2019@23:26:54 - ragavi       - ERROR      - Invalid DATA_DESC_ID, FIELD_ID, SCAN_NUMBER or TAQL clause
Traceback (most recent call last):
  File "/home/ianh/.local/lib/python2.7/site-packages/ragavi/visibilities.py", line 810, in get_ms
    chunks=chunks)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/dask_ms.py", line 291, in xds_from_ms
    **kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/dask_ms.py", line 229, in xds_from_table
    **kwargs).datasets()
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/reads.py", line 365, in datasets
    self.taql_where)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/ordering.py", line 78, in ordering_taql
    return TableProxy(taql_factory, query, tables=[table_proxy])
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 142, in __call__
    instance = type.__call__(cls, *args, **kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 207, in __init__
    table = ex.impl.submit(factory, *args, **kwargs).result()
  File "/home/ianh/.local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 462, in result
    return self.__get_result()
  File "/home/ianh/.local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 63, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ianh/.local/lib/python2.7/site-packages/daskms/table_proxy.py", line 187, in taql_factory
    return pt.taql(query, style=style, tables=tabs)
  File "/home/ianh/.local/lib/python2.7/site-packages/casacore/tables/table.py", line 153, in taql
    tab = table(cmd, tabs, _oper=2)
  File "/home/ianh/.local/lib/python2.7/site-packages/casacore/tables/table.py", line 328, in __init__
    Table.__init__(self, tablename, tabledesc)
RuntimeError: Error in TaQL command: 'using style Python SELECT
	ROWID() as __tablerow__
FROM
	$1
ORDERBY
	TIMEWHERE
	SCAN_NUMBER IN [10]'
  Error in select expression: TIMEWHERE is an unknown column (or keyword) in table /mnt/hgfs/heywood/Astro/Projects/VLA/3C31/spw01/2019/3C31.ms
```

**Comment by Mulan-94** [comment]
Hi @IanHeywood yes this was a bug in `dask-ms` that was recently resolved. I also note that you're using `Python2`. I suggest to create a `Python3` environment and reinstall `ragavi` and its requirements there, it should solve this problem.

**Comment by IanHeywood** [comment]
Thanks Lexy. I was testing this functionality as I was having trouble getting xarray-ms to respect taql queries in my own code, but the fact that I'm on python 2.7 and not using dask-ms suggests that I'm the problem here.

Cheers.

**Comment by Mulan-94** [comment]
@IanHeywood `xarray-ms` changed name to `dask-ms` and supports only `Python3` now I think.

**Comment by IanHeywood** [comment]
Yes, I just found this out the slow and frustrating way! :)
