### ISSUE TITLE
IndexError: list index out of range with 1.1.3

### ISSUE THREAD

**Issue by o-smirnov** [ratt-ru/ragavi#37]
Trying this out in MeerKATHI, but I get: 

```
-----------------------------------
Stimela version     : 1.0.1
Cab name            : stimela/ragavi:1.1.3
-------------------------------------
Running: ragavi --corr 0 --cmap coolwarm --doplot ap --field 6 --gaintype K --htmlname /scratch/output/reports/old-devils-1557766852_sdp_l0_1284.hh_vv-1gc1-K0 --table /scratch/output/caltables/old-devils-1557766852_sdp_l0_1284.hh_vv-1gc1.K0
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - xarrayms.xarray_ms - WARNING - Unable to infer shape of 'WEIGHT' column. Ignoring.
==================================== (O_o) =====================================
15.07.2019@14:24:05 - ragavi.vis_utils - ERROR - Oops ... !
Traceback (most recent call last):
  File "/usr/local/bin/ragavi", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1562, in main
    y1_err=y1_err, y2_err=y2_err)
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 609, in make_plots
    nonsel_glyph = markers[fid]()
IndexError: list index out of range
==================================== (O_o) =====================================
15.07.2019@14:24:05 - ragavi.vis_utils - ERROR - Oops ... !
Traceback (most recent call last):
  File "/usr/local/bin/ragavi", line 6, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1562, in main
    y1_err=y1_err, y2_err=y2_err)
  File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 609, in make_plots
    nonsel_glyph = markers[fid]()
IndexError: list index out of range
```

**Comment by Mulan-94** [comment]
@o-smirnov , I think this is now fixed.

**Comment by SpheMakh** [comment]
I can confirm that the fix works.
