### ISSUE TITLE
Not able to plot multiple fields 

### ISSUE THREAD

**Issue by SpheMakh** [ratt-ru/ragavi#42]
```
meerkathi - 2019-10-30 14:57:37,790 INFO - Running: ragavi --corr 0 --cmap coolwarm --doplot ap --field 2,6 --gaintype F --htmlname /home/sphe/output/reports/mypipelinerun-1557766852_32chan-1gc1-F0 --table /home/sphe/output/caltables/mypipelinerun-1557766852_32chan-1gc1.F0
meerkathi - 2019-10-30 14:57:37,790 INFO - ==================================== (O_o) =====================================
meerkathi - 2019-10-30 14:57:37,790 INFO - ==================================== (O_o) =====================================
meerkathi - 2019-10-30 14:57:37,790 INFO - ==================================== (O_o) =====================================
meerkathi - 2019-10-30 14:57:37,790 INFO - Traceback (most recent call last):
meerkathi - 2019-10-30 14:57:37,790 INFO -   File "/usr/local/bin/ragavi", line 6, in <module>
meerkathi - 2019-10-30 14:57:37,790 INFO -     main()
meerkathi - 2019-10-30 14:57:37,790 INFO -   File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1670, in main
meerkathi - 2019-10-30 14:57:37,790 INFO -     ax1_title = Title(text="{} vs {} ({})".format(ax1_ylabel,
meerkathi - 2019-10-30 14:57:37,790 INFO - UnboundLocalError: local variable 'ax1_ylabel' referenced before assignment
meerkathi - 2019-10-30 14:57:37,790 INFO - 
meerkathi - 2019-10-30 14:57:37,790 INFO - Traceback (most recent call last):
meerkathi - 2019-10-30 14:57:37,790 INFO -   File "/scratch/code/run.py", line 30, in <module>
meerkathi - 2019-10-30 14:57:37,790 INFO -     utils.xrun(cab['binary'], args)
meerkathi - 2019-10-30 14:57:37,790 INFO -   File "/scratch/stimela/utils/__init__.py", line 124, in xrun
meerkathi - 2019-10-30 14:57:37,790 INFO -     '%s: returns errr code %d' % (command, process.returncode))
meerkathi - 2019-10-30 14:57:37,790 INFO - utils.StimelaCabRuntimeError: ragavi: returns errr code 1
meerkathi - 2019-10-30 14:57:37,790 INFO - Stopping virtual X frame buffer: Xvfb
```

Zoom in on the error

```
File "/usr/local/lib/python2.7/dist-packages/ragavi/ragavi.py", line 1670, in main
meerkathi - 2019-10-30 14:57:37,790 INFO -     ax1_title = Title(text="{} vs {} ({})".format(ax1_ylabel,
meerkathi - 2019-10-30 14:57:37,790 INFO - UnboundLocalError: local variable 'ax1_ylabel' referenced before assignment
```

**Comment by SpheMakh** [comment]
My mistake. I gave a comma-separated string instead of a space-separated one

**Comment by Mulan-94** [comment]
> My mistake. I gave a comma-separated string instead of a space-separated one

Is it working with this though?

**Comment by SpheMakh** [comment]
yep!
