### ISSUE TITLE
ragavi-vis memory error

### ISSUE THREAD

**Issue by IanHeywood** [ratt-ru/ragavi#58]
My command was:

```
ragavi-vis --xaxis freq --yaxis amplitude --iter-axis scan --ms 1566542621_sdp_l0_wtspec_COSMOS_1.ms --corr 0
```

Here is the error:

```
04.04.2020@20:44:22 - ragavi       - INFO       - Chunk sizes: (100000, 1024, 4)
04.04.2020@20:44:22 - ragavi       - INFO       - Number of Partitions: 60
04.04.2020@20:44:22 - ragavi       - INFO       - Starting data processing.
04.04.2020@20:44:22 - ragavi       - INFO       - Starting plotting function.
04.04.2020@20:44:22 - ragavi       - INFO       - Calculating x and y Min and Max ranges
[########################################] | 100% Completed | 28min 29.0s
04.04.2020@21:12:51 - ragavi       - INFO       - Done
04.04.2020@21:12:51 - ragavi       - INFO       - Creating Dataframe
04.04.2020@21:28:41 - ragavi       - ERROR      - Oops ... !
Traceback (most recent call last):
  File "/users/ianh/venv/py3/bin/ragavi-vis", line 11, in <module>
    main(options=options)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/ragavi/visibilities.py", line 1440, in main
    colour_axis=colour_axis)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/ragavi/visibilities.py", line 1161, in hv_plotter
    xy_df[iterate] = xy_df[iterate].cat.as_known()
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/dataframe/categorical.py", line 189, in as_known
    categories = self._property_map("categories").unique().compute(**kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/array/chunk.py", line 263, in arange
    res = np.arange(start, stop, step, dtype)
MemoryError: Unable to allocate 45.4 GiB for an array with shape (6095736832,) and data type int64
```

Any suggestions? Would a smaller chunk size help?

Thanks.

**Comment by IanHeywood** [comment]
> Would a smaller chunk size help?

The answer is no. 45 MB is a big ask! 

```
04.04.2020@21:40:57 - ragavi       - INFO       - Chunk sizes: (1000, 1024, 4)
04.04.2020@21:40:57 - ragavi       - INFO       - Number of Partitions: 5953
04.04.2020@21:40:57 - ragavi       - INFO       - Starting data processing.
04.04.2020@21:40:57 - ragavi       - INFO       - Starting plotting function.
04.04.2020@21:40:57 - ragavi       - INFO       - Calculating x and y Min and Max ranges
[########################################] | 100% Completed | 27min 54.8s[
04.04.2020@22:08:53 - ragavi       - INFO       - Done
04.04.2020@22:08:53 - ragavi       - INFO       - Creating Dataframe
04.04.2020@22:30:30 - ragavi       - ERROR      - Oops ... !
Traceback (most recent call last):
  File "/users/ianh/venv/py3/bin/ragavi-vis", line 11, in <module>
    main(options=options)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/ragavi/visibilities.py", line 1440, in main
    colour_axis=colour_axis)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/ragavi/visibilities.py", line 1161, in hv_plotter
    xy_df[iterate] = xy_df[iterate].cat.as_known()
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/dataframe/categorical.py", line 189, in as_known
    categories = self._property_map("categories").unique().compute(**kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/base.py", line 437, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/threaded.py", line 84, in get
    **kwargs
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 486, in get_async
    raise_exception(exc, tb)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 316, in reraise
    raise exc
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/local.py", line 222, in execute_task
    result = _execute_task(task, data)
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in <genexpr>
    return func(*(_execute_task(a, cache) for a in args))
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/core.py", line 121, in _execute_task
    return func(*(_execute_task(a, cache) for a in args))
MemoryError: Unable to allocate 45.4 MiB for an array with shape (5952868,) and data type int64
Killed
```

**Comment by Mulan-94** [comment]
Hi @IanHeywood, sorry I'm just seeing this. I've never encountered this error before and have no idea how to reproduce it. Maybe how big is this dataset?

**Comment by IanHeywood** [comment]
Thanks Lexy. 

The MS is 367GB (a standard ~8 hour MeerKAT track, minus calibrator scans and averaged to 1,024 channels), although only about a third of that is the DATA column.

I tried without iteration and it died in more mysterious circumstances.

```
04.04.2020@22:57:08 - ragavi       - INFO       - Chunk sizes: (100000, 1024, 4)
04.04.2020@22:57:08 - ragavi       - INFO       - Number of Partitions: 60
04.04.2020@22:57:08 - ragavi       - INFO       - Starting data processing.
04.04.2020@22:57:08 - ragavi       - INFO       - Starting plotting function.
04.04.2020@22:57:08 - ragavi       - INFO       - Calculating x and y Min and Max ranges
[########################################] | 100% Completed | 20min 44.5s
04.04.2020@23:17:53 - ragavi       - INFO       - Done
04.04.2020@23:17:53 - ragavi       - INFO       - Creating Dataframe
Killed
```

I'm working on an IDIA node, so probably don't have permission for config changes, although we can ask for them if they're well motivated.

**Comment by Mulan-94** [comment]
@sjperkins @JSKenyon Please help. Have you encountered this error before with `dask`?

**Comment by IanHeywood** [comment]
shadeMS fails in the same way:

```
shadems --xaxis f --yaxis a --corr 0 1566542621_sd_
2020-04-05 14:07:16,685 - shadems - INFO - Plotting Amplitude vs Frequency
2020-04-05 14:07:16,685 - shadems - INFO - Correlation index 0
2020-04-05 14:07:17,404 - shadems - INFO -
2020-04-05 14:07:17,404 - shadems - INFO - FIELD_ID   NAME
2020-04-05 14:07:17,404 - shadems - INFO - 0          COSMOS_1
2020-04-05 14:07:17,405 - shadems - INFO -
2020-04-05 14:07:17,405 - shadems - INFO - SPW_ID     NCHAN
2020-04-05 14:07:17,412 - shadems - INFO - 0          1024
2020-04-05 14:07:17,412 - shadems - INFO -
2020-04-05 14:07:17,413 - shadems - INFO - Reading 1566542621_sdp_l0_wtspec_COSMOS_1.ms
2020-04-05 14:07:17,413 - shadems - INFO - DATA column
2020-04-05 14:07:19,488 - shadems - INFO - Rearranging the deck chairs
Traceback (most recent call last):
  File "/users/ianh/venv/shade/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/ShadeMS/main.py", line 195, in main
    nrows = group.VISDATA.values.shape[0]
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/xarray/core/dataarray.py", line 558, in values
    return self.variable.values
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/xarray/core/variable.py", line 446, in values
    return _as_array_or_item(self._data)
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/xarray/core/variable.py", line 249, in _as_array_or_item
    data = np.asarray(data)
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/numpy/core/_asarray.py", line 85, in asarray
    return array(a, dtype, copy=False, order=order)
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/array/core.py", line 1337, in __array__
    x = self.compute()
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/base.py", line 166, in compute
    (result,) = compute(self, traverse=False, **kwargs)
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/base.py", line 438, in compute
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/base.py", line 438, in <listcomp>
    return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/array/core.py", line 987, in finalize
    return concatenate3(results)
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/dask/array/core.py", line 4371, in concatenate3
    result = np.empty(shape=shape, dtype=dtype(deepfirst(arrays)))
MemoryError: Unable to allocate 182. GiB for an array with shape (5952868, 1024, 4) and data type complex64
```

**Comment by JSKenyon** [comment]
This usually happens when an array is simply too large to be allocated. That can be because of contested resources/arrays genuinely being enormous. The error with the smaller chunks is more confusing.

**Comment by JSKenyon** [comment]
Can you watch htop carefully as this runs @IanHeywood? I wouldn't be surprised if the problem stems from some other piece of code/dask misbehaving.

**Comment by sjperkins** [comment]
@IanHeywood Calling **.values** on the xarray DataArray reifies the underlying dask array and produces a numpy array. 

```python
Traceback (most recent call last):
  File "/users/ianh/venv/shade/bin/shadems", line 8, in <module>
    main.main([a for a in sys.argv[1:]])
  File "/users/ianh/venv/shade/lib/python3.6/site-packages/ShadeMS/main.py", line 195, in main
    nrows = group.VISDATA.values.shape[0]
```

You probably want to change the above line to

```python
nrows = group.VISDATA.shape[0]
```

**Comment by sjperkins** [comment]
@Mulan-94 This line seems to be the issue, the dataframe is getting computed (reified) and the entire result placed in memory.

```python
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/ragavi/visibilities.py", line 1161, in hv_plotter
    xy_df[iterate] = xy_df[iterate].cat.as_known()
  File "/users/ianh/venv/py3/lib/python3.6/site-packages/dask/dataframe/categorical.py", line 189, in as_known
    categories = self._property_map("categories").unique().compute(**kwargs)
```

I am not very familiar with datashader and it's use of (dask?) dataframes myself. Is there not some way to avoid computing the dataframe?

Just to briefly recap the dask paradigm. One (https://docs.dask.org/en/latest/user-interfaces.html#lazy-vs-immediate) -- the computation only happens when compute is called.

One needs to be judicious when constructing the graph and with the potential result.

1. the dask arrays are chunked. Operations are separately performed on each chunk allowing both out-of-core and parallel computation.
2. in general, the final result should be computed and should be as small as possible.

dask-ms provides the basis for (1) but I think both ragavi and shadems are running into problems around (2). Computation is happening too early and the result is too large. This might be because of how datashader is used in these instances. Without having a good understanding of the code, I think that the right way to solve this is to determine how to retain dask's laziness within the datashader paradigm.

**Comment by IanHeywood** [comment]
Thanks @sjperkins. A re-write of shadeMS that uses dask properly has been on my to-do list since your tutorial in Cape Town some months ago, it just hasn't floated to the top of it yet. The two open issues over there are both related to this.

https://github.com/IanHeywood/shadeMS/issues/
