### ISSUE TITLE
ImportError: cannot import name 'chan_metadata'

### ISSUE THREAD

**Issue by viralp** [ratt-ru/ragavi#83]
Hi. Getting the following error

03.03.2021@20:20:59 - ragavi               - ERROR      - Oops ... uncaught exception occurred!
03.03.2021@20:20:59 - ragavi               - ERROR      - Traceback (most recent call last):
03.03.2021@20:20:59 - ragavi               - ERROR      -    File "/home/vparekh/venv/bin/ragavi-vis", line 20, in <module>
03.03.2021@20:20:59 - ragavi               - ERROR      -     from ragavi.visibilities import main
03.03.2021@20:20:59 - ragavi               - ERROR      -    File "/home/vparekh/venv/lib/python3.6/site-packages/ragavi/visibilities.py", line 34, in <module>
03.03.2021@20:20:59 - ragavi               - ERROR      -     from ragavi.averaging import get_averaged_ms
03.03.2021@20:20:59 - ragavi               - ERROR      -    File "/home/vparekh/venv/lib/python3.6/site-packages/ragavi/averaging.py", line 21, in <module>
03.03.2021@20:20:59 - ragavi               - ERROR      -     from africanus.averaging.dask import (time_and_channel,
03.03.2021@20:20:59 - ragavi               - ERROR      -  ImportError: cannot import name 'chan_metadata'

**Comment by Mulan-94** [comment]
Hi @viralp , please could you provide the command you used so that I can try to replicate this?
In the meantime, I'm assuming this is from `caracal`, you could switch the standard plotter to: `shadems`
